apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.service_name }}
    template: {{ .Values.service_name }}
  name: {{ .Values.service_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.service_name }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        last-updated-epoch: {{ now | unixEpoch | quote }}
      labels:
        app: {{ .Values.service_name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.secret_name }}
      containers:
      - image: {{ .Values.docker_image }}
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - cat
            - /etc/hosts
          initialDelaySeconds: 90
          periodSeconds: 20
        name: {{ .Values.service_name }}
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - cat
            - /etc/hosts
          initialDelaySeconds: 90
          periodSeconds: 20
        resources:
          limits:
            cpu: 300m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 200Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
status: {}
